import type { Project, ArchitectureFlowNode } from "../types";
import { CATALOG } from "../catalog";
import { lintArchitecture } from "../linter";

function nodeName(n: ArchitectureFlowNode): string {
  return n.data.name || CATALOG[n.data.architectureType].label;
}

/** Generate a Markdown design doc from a project. */
export function projectToMarkdown(project: Project): string {
  const { brief, nodes, edges, decisions } = project;
  const byId = new Map(nodes.map((n) => [n.id, n]));
  const lines: string[] = [];

  lines.push(`# ${project.name}`);
  if (project.description) lines.push(`\n${project.description}`);
  lines.push(`\n_Status: ${project.status}_`);

  // Brief
  lines.push(`\n## Architecture brief\n`);
  if (brief.productGoal) lines.push(`- **Goal:** ${brief.productGoal}`);
  if (brief.users) lines.push(`- **Users:** ${brief.users}`);
  if (brief.coreFlows.length)
    lines.push(`- **Core flows:** ${brief.coreFlows.join("; ")}`);
  if (brief.trafficAssumptions)
    lines.push(`- **Traffic:** ${brief.trafficAssumptions}`);
  lines.push(`- **Data sensitivity:** ${brief.dataSensitivity}`);
  lines.push(`- **Availability:** ${brief.availability}`);
  if (brief.latencyNeeds) lines.push(`- **Latency:** ${brief.latencyNeeds}`);
  if (brief.integrations.length)
    lines.push(`- **Integrations:** ${brief.integrations.join(", ")}`);
  if (brief.compliance.length)
    lines.push(`- **Compliance:** ${brief.compliance.join(", ")}`);

  // Components
  lines.push(`\n## Components\n`);
  if (nodes.length === 0) {
    lines.push("_No components yet._");
  } else {
    for (const n of nodes) {
      const entry = CATALOG[n.data.architectureType];
      lines.push(`### ${nodeName(n)} (${entry.label})`);
      if (n.data.technology) lines.push(`- **Technology:** ${n.data.technology}`);
      if (n.data.description) lines.push(`- **Purpose:** ${n.data.description}`);
      if (n.data.owner) lines.push(`- **Owner:** ${n.data.owner}`);
      if (n.data.dataStored.length)
        lines.push(`- **Data stored:** ${n.data.dataStored.join(", ")}`);
      if (n.data.scalingStrategy)
        lines.push(`- **Scaling:** ${n.data.scalingStrategy}`);
      if (n.data.failureMode)
        lines.push(`- **Failure behavior:** ${n.data.failureMode}`);
      if (n.data.cacheInvalidationStrategy)
        lines.push(`- **Cache invalidation:** ${n.data.cacheInvalidationStrategy}`);
      if (n.data.securityNotes.length)
        lines.push(`- **Security:** ${n.data.securityNotes.join("; ")}`);
      if (n.data.costNotes.length)
        lines.push(`- **Cost:** ${n.data.costNotes.join("; ")}`);
      lines.push("");
    }
  }

  // Connections
  if (edges.length > 0) {
    lines.push(`## Connections\n`);
    for (const e of edges) {
      const from = byId.get(e.source);
      const to = byId.get(e.target);
      if (!from || !to) continue;
      const label = e.data?.description ? ` - ${e.data.description}` : "";
      lines.push(`- ${nodeName(from)} → ${nodeName(to)}${label}`);
    }
    lines.push("");
  }

  // Data ownership
  const owners = nodes.filter((n) => n.data.dataStored.length > 0);
  if (owners.length > 0) {
    lines.push(`## Data ownership\n`);
    for (const n of owners) {
      lines.push(`- **${nodeName(n)}:** ${n.data.dataStored.join(", ")}`);
    }
    lines.push("");
  }

  // Decisions
  if (decisions.length > 0) {
    lines.push(`## Decision records\n`);
    for (const d of decisions) {
      lines.push(`### ${d.title} (${d.status})`);
      if (d.context) lines.push(`**Context:** ${d.context}`);
      if (d.decision) lines.push(`\n**Decision:** ${d.decision}`);
      if (d.alternatives.length)
        lines.push(`\n**Alternatives:** ${d.alternatives.join(", ")}`);
      if (d.tradeoffs.length)
        lines.push(`\n**Trade-offs:** ${d.tradeoffs.join("; ")}`);
      lines.push("");
    }
  }

  // Review findings
  const findings = lintArchitecture({ brief, nodes });
  if (findings.length > 0) {
    lines.push(`## Review findings\n`);
    for (const f of findings) {
      lines.push(
        `- **[${f.severity.toUpperCase()}] ${f.title}** - ${f.description} _${f.recommendation}_`
      );
    }
    lines.push("");
    lines.push(`## Suggested next steps\n`);
    findings.forEach((f, i) => lines.push(`${i + 1}. ${f.recommendation}`));
  }

  lines.push(`\n---\n_Generated by System Atlas._`);
  return lines.join("\n");
}
